apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cryptobom-oss.fullname" . }}-config
  labels:
    {{- include "cryptobom-oss.labels" . | nindent 4 }}
data:
  SERVICE_NAME: "cryptobom-oss"
  VERSION: {{ .Chart.AppVersion | quote }}
  PORT: "8080"
  DEBUG: "false"
  DATABASE_SSLMODE: "require"
  OBSERVABILITY_METRICS_ENABLED: "true"
  DEMO_MODE: {{ .Values.global.demoMode | default false | quote }}
