// Generated by create-react-app v5.0.1

import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { ThemeProvider, createTheme } from '@mui/material/styles';
import { CssBaseline, GlobalStyles } from '@mui/material';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import App from './App';
import reportWebVitals from './reportWebVitals';

// Create a theme for the application
const theme = createTheme({
  palette: {
    mode: 'light',
    primary: {
      main: '#667eea', // RivicQ brand color
      dark: '#4c63d2',
      contrastText: '#ffffff',
    },
    secondary: {
      main: '#764ba2', // Secondary purple
      dark: '#553c9a',
      contrastText: '#ffffff',
    },
    background: {
      default: '#f5f5f5',
      paper: '#ffffff',
    },
    text: {
      primary: 'rgba(0, 0, 0, 0.87)',
      secondary: 'rgba(0, 0, 0, 0.6)',
    },
    success: {
      main: '#10b981', // Green for success
      dark: '#0d8040',
    },
    warning: {
      main: '#ff9800', // Orange for warnings
      dark: '#f57c00',
    },
    error: {
      main: '#f44336', // Red for errors
      dark: '#d32f2f',
    },
    info: {
      main: '#2196f3', // Blue for info
      dark: '#0d47a1',
    },
  },
  typography: {
    fontFamily: '"Inter", "Roboto", "Helvetica", "Arial", sans-serif',
  },
  components: {
    MuiButton: {
      styleOverrides: {
        root: {
          textTransform: 'none',
          borderRadius: 8,
        },
      },
    },
  },
});

// Create React Query client with optimized defaults
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 60 * 1000, // 1 minute
      cacheTime: 5 * 60 * 1000, // 5 minutes
      retry: 2,
      refetchOnWindowFocus: false,
    },
  },
});

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);

root.render(
  <React.StrictMode>
    <QueryClientProvider client={queryClient}>
      <BrowserRouter>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <GlobalStyles
            styles={{
              body: {
                margin: 0,
                fontFamily: theme.typography.fontFamily,
                backgroundColor: theme.palette.background.default,
                color: theme.palette.text.primary,
                lineHeight: 1.6,
              },
              '*': {
                boxSizing: 'border-box',
              },
              '::-webkit-scrollbar': {
                width: '8px',
                height: '8px',
              },
              '::-webkit-scrollbar-track': {
                background: theme.palette.background.paper,
              },
              '::-webkit-scrollbar-thumb': {
                background: theme.palette.divider,
                borderRadius: '4px',
              },
              '::-webkit-scrollbar-thumb:hover': {
                background: theme.palette.action.hover,
              },
            }}
          />
          <App />
          <ToastContainer
            position="top-right"
            theme="colored"
            newestOnTop={true}
            pauseOnFocus={false}
            autoClose={5000}
            hideProgressBar={false}
          />
        </ThemeProvider>
      </BrowserRouter>
    </QueryClientProvider>
    <ReactQueryDevtools initialIsOpen={false} />
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals(console.log);