apiVersion: v1
kind: Namespace
metadata:
  name: cryptobom-system
  labels:
    app.kubernetes.io/name: cryptobom
    app.kubernetes.io/managed-by: Helm
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
