apiVersion: v1
kind: Service
metadata:
  name: cryptobom-server
  namespace: cryptobom-system
  labels:
    app: cryptobom-server
spec:
  selector:
    app: cryptobom-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cryptobom-server-lb
  namespace: cryptobom-system
  labels:
    app: cryptobom-server
spec:
  selector:
    app: cryptobom-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
