apiVersion: v1
kind: Service
metadata:
  name: cryptobom-server
  namespace: cryptobom-system
  labels:
    app: cryptobom-server
spec:
  type: ClusterIP
  selector:
    app: cryptobom-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cryptobom-server-lb
  namespace: cryptobom-system
  labels:
    app: cryptobom-server
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: cryptobom-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
